export const LOGIN = {
    LOGIN: 'LOGIN_LOGIN'
}

export const ADD_APPLICATION = {
    LEAVE_TYPE: 'LEAVE_TYPE',
    START_DATE: 'START_DATE',
    END_DATE: 'END_DATE',
    FILES_UPLOAD: 'FILES_UPLOAD',
    APPLICATION_SUBMIT: 'APPLICATION_SUBMIT'
}

export const GET_APPLICATIONS = {
    APPLICATIONS: 'APPLICATIONS',
    UPDATE_APPLICATIONS: 'UPDATE_APPLICATIONS'
}

export const SIGNUP = {
    SIGNUP: 'SIGNUP_SIGNUP'
}