export const LOGIN = {
    LOGIN: 'LOGIN_LOGIN'
}

export const ADD_APPLICATION = {
    LEAVE_TYPE: 'LEAVE_TYPE',
    START_DATE: 'START_DATE',
    END_DATE: 'END_DATE',
    FILES_UPLOAD: 'FILES_UPLOAD'
}